export { default as About } from './about/About'
export { default as Navbar } from './navbar/Navbar'
export { default as Projects } from './projects/Projects'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'